import React,{useEffect,useMemo,useState}from'react';
import{useLocation,useNavigate}from'react-router-dom';
import{persistAttribution,getAttribution,getConsent,setConsent,track,acknowledgeConversion}from'./analytics';
import'./styles.css';

const packages=[
  ['Intelligence','$2,500 / month','For teams that need clearer buyer, account, buying-context and intent intelligence before expanding into managed activation.',['Audience Intelligence','ICP and account segmentation','Account Intelligence','Buying-group context','Intent Intelligence','Evidence Graph']],
  ['Intelligence + Activation','$5,000 / month','For GTM teams ready to translate intelligence into coordinated demand, ABM and sales execution.',['Everything in Intelligence','GTM activation workflows','Account prioritization','Demand / ABM orchestration','Evidence-rich sales handoff','Campaign measurement framework','Agreed managed activation support']],
  ['Enterprise GTM','Custom','For complex multi-team, multi-market or integration-heavy GTM environments.',['Expanded intelligence scope','Managed GTM programs','Strategic advisory','Research and intelligence','Executive programs','Approved enterprise integrations','Advanced governance and measurement design']]
];

const pageMap={
  '/':{eyebrow:'BUYER INTELLIGENCE + PIPELINE ACTIVATION',h1:'KNOW WHO IS MOVING. KNOW WHY. ACT WHILE IT MATTERS.',lede:'Intent Amplify connects account, buying-group, intent and engagement signals into traceable buyer evidence—so GTM teams can identify active demand, understand why an account deserves attention and coordinate the next action.',sections:[['YOUR GTM STACK CAPTURES ACTIVITY. THE CHALLENGE IS KNOWING WHAT MATTERS.','CRM, marketing automation, websites, content, events, intent providers and sales systems each capture part of the buying journey. Intent Amplify connects that activity around accounts and buying contexts so teams can decide what deserves attention.'],['EVERY PRIORITY SHOULD BE EXPLAINABLE.','See the observations, sources, timing and context behind an account priority or recommendation.'],['PUT BUYER INTELLIGENCE INTO MOTION.','Coordinate demand, ABM, content, event and sales workflows without losing the evidence and permission context behind the decision.']],primary:['Book a Demo','/book-demo/'],secondary:['Explore the Platform','/platform/']},
  '/platform/':{eyebrow:'INTENT AMPLIFY PLATFORM',h1:'TURN BUYER SIGNALS INTO EXPLAINABLE GTM ACTION.',lede:'Intent Amplify connects audiences, accounts, buying groups, intent and engagement into traceable buyer evidence—then helps GTM teams prioritize, activate and measure the next motion.',sections:[['Audience Intelligence','Define the market and accounts before activation.'],['Account + Buying Group Intelligence','Bring fit, relevant roles, topics, engagement, intent and timing into one decision surface while separating observed participation from inferred relevance.'],['Evidence + Activation','Make the evidence behind priority visible, then coordinate the approved next motion.']],primary:['Book a Demo','/book-demo/'],secondary:['View Pricing','/pricing/']},
  '/platform/buyer-intelligence/':{eyebrow:'AUDIENCE INTELLIGENCE',h1:'BUILD THE AUDIENCE BEFORE YOU BUILD THE CAMPAIGN.',lede:'Define the market you want to win, identify the accounts and buying contexts that fit, and build activation-ready audiences around explicit GTM priorities.',sections:[['Market definition','Start with ICP, market and account criteria rather than channel activity.'],['Buying context','Connect account fit with relevant roles and observed evidence without inferring sensitive traits.']],primary:['Explore Intent Intelligence','/platform/intent-signals/'],secondary:['Book a Demo','/book-demo/']},
  '/platform/audience-builder/':{eyebrow:'ACCOUNT + BUYING GROUP INTELLIGENCE',h1:'SEE WHAT IS CHANGING INSIDE THE ACCOUNT.',lede:'Bring account fit, relevant roles, topics, engagement, intent and timing into one view—while keeping observed participation separate from inferred buying-group relevance.',sections:[['Account context','See which signals and topics are changing around the account.'],['Buying-group context','Connect relevant roles to account evidence without asserting unverified participation.']],primary:['Explore Evidence Graph','/evidence-graph/'],secondary:['Book a Demo','/book-demo/']},
  '/platform/intent-signals/':{eyebrow:'INTENT INTELLIGENCE',h1:'INTENT YOU CAN INSPECT—NOT JUST ACCEPT.',lede:'Understand what changed, when it changed, which evidence contributed and which account or buying context is involved before deciding how GTM should respond.',sections:[['Signal provenance','Keep source, timestamp, recency and context visible.'],['Qualification boundary','Intent can inform prioritization. It does not automatically create an MQL, SQL, opportunity or purchase-readiness state.']],primary:['Inspect the Evidence Graph','/evidence-graph/'],secondary:['View Data Methodology','/trust/data-methodology/']},
  '/evidence-graph/':{eyebrow:'EVIDENCE GRAPH — DEMO/STAGING',h1:'EVERY PRIORITY SHOULD BE EXPLAINABLE.',lede:'See the observations, sources, timing and context behind an account priority or recommendation. Any illustrative account journey on staging is DEMO DATA unless backed by approved live evidence.',sections:[['Observed ≠ Inferred','Keep direct observations separate from interpreted or recommended outputs.'],['Identity ≠ Permission','Identity resolution and activation permission remain separate controls.'],['Intent ≠ MQL ≠ SQL','Evidence can support prioritization; qualification states remain governed downstream.']],primary:['Explore Activation','/platform/activation/'],secondary:['View Trust & Data','/trust/']},
  '/platform/activation/':{eyebrow:'ACTIVATION',h1:'PUT BUYER INTELLIGENCE INTO MOTION.',lede:'Turn prioritized accounts, buying context and relevant evidence into coordinated demand, ABM, content, event and sales workflows without losing source or permission context.',sections:[['Evidence to motion','Carry the why-now context into the next approved GTM action.'],['Managed activation','Use managed GTM programs where execution support is required.']],primary:['Explore Programs','/programs/'],secondary:['Book a Demo','/book-demo/']},
  '/platform/pipeline-intelligence/':{eyebrow:'MEASUREMENT',h1:'MEASURE ACCOUNT PROGRESSION—NOT JUST CAMPAIGN ACTIVITY.',lede:'Connect approved website, campaign and account context to governed progression without turning observation into automatic qualification or attribution.',sections:[['Lifecycle boundaries','Form submission, MQL, SAL, SQL, Opportunity and revenue remain distinct states.'],['Evidence before attribution','Use source-system evidence before making pipeline, revenue or attribution claims.']],primary:['Explore SignalAtlas','/signalatlas/'],secondary:['View Trust & Data','/trust/']},
  '/signalatlas/':{eyebrow:'POWERED BY INTENT AMPLIFY',h1:'SEE HOW BUYER ENGAGEMENT CHANGES OVER TIME.',lede:'SignalAtlas is the measurement and journey-intelligence capability within the Intent Amplify ecosystem. It brings approved digital engagement, campaign activity and account context into a governed measurement layer without turning observation into automatic qualification or attribution.',sections:[['Account-aware visibility','Understand engagement patterns around accounts while preserving identity and consent boundaries.'],['DEMO/STAGING DATA','Illustrative journeys, priorities, buying-group roles, scores or recommendations are labeled demo-only unless authoritative evidence supports them.'],['CRM authority stays downstream','SignalAtlas informs measurement; CRM remains authoritative for governed lifecycle and revenue states.']],primary:['Book a Demo','/book-demo/'],secondary:['View Trust & Data','/trust/']},
  '/solutions/':{eyebrow:'SOLUTIONS',h1:'SOLVE THE GTM DECISION YOUR TEAM IS STUCK ON.',lede:'Align marketing, demand, ABM, RevOps and sales around the same account evidence while giving each team the context it needs to decide what to do next.',sections:[['CMO','Make GTM investment more accountable.'],['Demand + ABM','Build demand around the accounts that matter and make priority explainable.'],['RevOps + Sales','Give GTM data one operating language and sellers the why-now context.']],primary:['Explore the Platform','/platform/'],secondary:['Book a Demo','/book-demo/']},
  '/solutions/cmo/':{eyebrow:'FOR CMOs',h1:'MAKE GTM INVESTMENT MORE ACCOUNTABLE.',lede:'Give marketing a clearer view of the market, active accounts, buying context, program activity and account progression—without overstating causation or attribution.',sections:[['Portfolio view','Connect market, account, program and evidence context.'],['Governed proof','Keep performance and attribution claims tied to authoritative evidence.']],primary:['Book a Demo','/book-demo/'],secondary:['Explore the Platform','/platform/']},
  '/solutions/demand-generation/':{eyebrow:'DEMAND GENERATION',h1:'BUILD DEMAND AROUND THE ACCOUNTS THAT MATTER.',lede:'Build demand programs around ICP fit, active buying evidence and relevant account context—not activity volume alone.',sections:[['Account first','Prioritize accounts and buying context before channel execution.'],['Handoff boundary','Pass evidence to SDR and sales without manufacturing MQL or SQL states from web behavior.']],primary:['Book a Demo','/book-demo/'],secondary:['Explore Audience Intelligence','/platform/buyer-intelligence/']},
  '/solutions/account-based-marketing/':{eyebrow:'ABM',h1:'ABM STARTS WITH ACCOUNT EVIDENCE.',lede:'Know which accounts deserve investment, understand their buying context and coordinate engagement around the roles, topics and evidence that matter.',sections:[['Account selection','Use explicit account and buying-context evidence.'],['Activation + SDR alignment','Coordinate around the same why-now context without auto-qualification.']],primary:['Explore Account Intelligence','/platform/audience-builder/'],secondary:['Book a Demo','/book-demo/']},
  '/solutions/revops/':{eyebrow:'REVOPS',h1:'GIVE GTM DATA ONE OPERATING LANGUAGE.',lede:'Create explicit boundaries between signal, evidence, intent, qualification, opportunity, pipeline and revenue while preserving source and permission context.',sections:[['Lifecycle semantics','Keep MQL, SAL, SQL, Opportunity and revenue definitions authoritative.'],['Source context','Preserve attribution and evidence provenance through the handoff.']],primary:['View Data Methodology','/trust/data-methodology/'],secondary:['Book a Demo','/book-demo/']},
  '/solutions/sales/':{eyebrow:'SALES',h1:'KNOW WHY THIS ACCOUNT DESERVES YOUR ATTENTION.',lede:'Give sellers recent account evidence, buying context, relevant roles and why-now rationale so outreach begins with more than a name and a score.',sections:[['Evidence brief','Bring together the account context relevant to outreach.'],['Sales authority','Qualification remains governed by the approved sales process and CRM state.']],primary:['Book a Demo','/book-demo/'],secondary:['Explore Evidence Graph','/evidence-graph/']},
  '/solutions/cybersecurity-gtm/':{eyebrow:'CYBERSECURITY GTM',h1:'BUYER EVIDENCE FOR COMPLEX CYBERSECURITY DECISIONS.',lede:'Connect domain research, buying-group context and governed activation for cybersecurity markets without publishing unsupported performance, dark-web or capability claims.',sections:[['Complex buying context','Security decisions may involve technical, risk, operations and executive roles.'],['Evidence boundary','Only verified sources and approved capabilities should support public claims.']],primary:['Explore Cybersecurity','/industries/cybersecurity/'],secondary:['Book a Demo','/book-demo/']},
  '/solutions/intent-driven-activation/':{eyebrow:'INTENT-DRIVEN ACTIVATION',h1:'MOVE FROM SIGNAL DETECTION TO COORDINATED ACTION.',lede:'Translate observed context into an actionable segment, then choose the approved narrative, channel and handoff path.',sections:[['Signal to audience','Use source and timing context to shape the segment.'],['Audience to motion','Activate only through supported, permitted workflows.']],primary:['Explore Activation','/platform/activation/'],secondary:['Book a Demo','/book-demo/']},
  '/solutions/pipeline-acceleration/':{eyebrow:'PIPELINE PROGRESSION',h1:'GIVE REVENUE TEAMS THE CONTEXT TO PROGRESS QUALIFIED OPPORTUNITIES.',lede:'Use evidence and CRM-authoritative opportunity context to support progression without inventing velocity, revenue or attribution claims.',sections:[['Opportunity context','Surface evidence relevant to an existing qualified motion.'],['Governed measurement','Keep reporting tied to authoritative CRM state.']],primary:['Explore Measurement','/platform/pipeline-intelligence/'],secondary:['Book a Demo','/book-demo/']},
  '/solutions/events-webinars/':{eyebrow:'EVENTS + WEBINARS',h1:'TURN EVENTS INTO OBSERVABLE BUYING-GROUP ENGAGEMENT.',lede:'Connect audience, registration, attendance, engagement, follow-up and CRM linkage as separate evidence steps.',sections:[['Before the event','Build the right audience and narrative.'],['After the event','Capture engagement and route evidence without equating attendance to qualification.']],primary:['Explore Resources','/resources/'],secondary:['Book a Demo','/book-demo/']},
  '/solutions/sales-development/':{eyebrow:'SALES DEVELOPMENT',h1:'GIVE SDRS EVIDENCE BEFORE THE FIRST CONVERSATION.',lede:'Deliver account, persona and signal context before outreach while keeping sales qualification authoritative.',sections:[['Evidence brief','Give SDRs the reason an account deserves attention.'],['Feedback loop','Return accepted or rejected context to the measurement layer.']],primary:['Book a Demo','/book-demo/'],secondary:['Explore Evidence Graph','/evidence-graph/']},
  '/programs/':{eyebrow:'MANAGED GTM PROGRAMS',h1:'MANAGED GTM PROGRAMS BUILT AROUND BUYER EVIDENCE.',lede:'Start with intelligence. Activate through the right motion. Measure what happens next.',sections:[['Demand + ABM programs','Translate account intelligence into coordinated programs with agreed scope.'],['Events + content programs','Use research, content and event motions where they support the buying context.'],['Sales handoff','Carry evidence into the approved sales workflow without promising qualification outcomes.']],primary:['Book a Demo','/book-demo/'],secondary:['View Pricing','/pricing/']},
  '/research/':{eyebrow:'RESEARCH & INSIGHTS',h1:'RESEARCH THAT SHARPENS GTM DECISIONS.',lede:'Combine market, buyer, account and competitive intelligence to understand where opportunity may exist and how GTM strategy should respond.',sections:[['Research library','Reports, whitepapers, ebooks and evidence-led editorial content.'],['Decision support','Use research to define the market, explain account context and improve GTM choices.']],primary:['Explore Resources','/resources/'],secondary:['Book a Demo','/book-demo/']},
  '/resources/':{eyebrow:'RESOURCES',h1:'INTELLIGENCE FOR THE GTM DECISION IN FRONT OF YOU.',lede:'Move from learning to understanding, inspect the evidence and methodology behind a topic, then explore the relevant Intent Amplify capability or start a GTM conversation.',sections:[['Learn','Build market and problem context.'],['Understand','Connect the topic to buying and account context.'],['Act with evidence','Move into capability exploration or a GTM conversation without treating content engagement as qualification.']],primary:['Explore the Platform','/platform/'],secondary:['Book a Demo','/book-demo/']},
  '/industries/':{eyebrow:'INDUSTRIES',h1:'APPLY BUYER INTELLIGENCE TO THE MARKET CONTEXT YOU SELL INTO.',lede:'Use the same evidence-led operating model across industry contexts while keeping domain-specific claims verified and governed.',sections:[['Cybersecurity','Complex committees, technical risk and evidence-sensitive buying.'],['Enterprise technology','Multi-stakeholder evaluation and integration-heavy buying.'],['SaaS, AI and digital markets','Fast-moving categories where signal quality and context matter.']],primary:['Explore the Platform','/platform/'],secondary:['Book a Demo','/book-demo/']},
  '/industries/cybersecurity/':{eyebrow:'CYBERSECURITY',h1:'NAVIGATE COMPLEX CYBERSECURITY BUYING WITH BETTER ACCOUNT EVIDENCE.',lede:'Security purchases can involve technical, risk, operations and executive stakeholders. Build the audience around the buying context, align the narrative to evidence and give sales context before outreach.',sections:[['Buying context','Map relevant roles and account evidence without inventing participation.'],['Domain research','Use approved cybersecurity research and content where relevant.']],primary:['Explore Cybersecurity GTM','/solutions/cybersecurity-gtm/'],secondary:['Book a Demo','/book-demo/']},
  '/industries/saas/':{eyebrow:'SAAS + CLOUD',h1:'PRIORITIZE SAAS DEMAND WITH ACCOUNT AND BUYING-CONTEXT EVIDENCE.',lede:'Use account and buying-context evidence to focus SaaS GTM motions without treating product interest as automatic qualification.',sections:[['Market context','Define the account universe around the buying problem.'],['Relevant motion','Connect signals to demand, ABM and measurement.']],primary:['Explore the Platform','/platform/'],secondary:['Book a Demo','/book-demo/']},
  '/industries/ai/':{eyebrow:'DATA + AI',h1:'FIND AND ACT ON EMERGING AI DEMAND WITH EVIDENCE.',lede:'Use observable market and buying-context evidence to guide AI-focused GTM action while separating interest from qualification.',sections:[['Emerging demand','Prioritize explainable evidence over hype.'],['Governed activation','Connect account context to the approved next motion.']],primary:['Explore the Platform','/platform/'],secondary:['Book a Demo','/book-demo/']},
  '/industries/fintech/':{eyebrow:'DIGITAL ASSETS + FINTECH',h1:'ALIGN GTM TO COMPLEX DIGITAL-FINANCE BUYING CONTEXT.',lede:'Use account, committee and intent context to guide GTM decisions without asserting unsupported wallet, on-chain or regulated-data capabilities.',sections:[['Buying complexity','Map business, technical and risk context.'],['Evidence-led motion','Connect verified observations to governed activation.']],primary:['Explore the Platform','/platform/'],secondary:['Book a Demo','/book-demo/']},
  '/company/about/':{eyebrow:'ABOUT INTENT AMPLIFY',h1:'BUILT TO MAKE B2B GTM MORE EVIDENCE-DRIVEN.',lede:'Intent Amplify is a buyer-intelligence and pipeline-activation company. We connect fragmented buyer signals into usable account and buying-context intelligence, make the evidence behind prioritization visible, and help GTM teams coordinate the next motion.',sections:[['Operating philosophy','Evidence before activation. Every priority should be explainable.'],['Brand architecture','Intent Amplify is the master GTM brand; SignalAtlas is the measurement and journey-intelligence capability within its ecosystem.']],primary:['Explore the Platform','/platform/'],secondary:['Contact Us','/contact/']},
  '/company/brands/':{eyebrow:'BRAND ARCHITECTURE',h1:'ONE GTM COMPANY. CLEARLY DEFINED CAPABILITIES.',lede:'Intent Amplify is the primary GTM brand. SignalAtlas is the measurement and journey-intelligence capability within the Intent Amplify ecosystem. CyberTech Intelligence remains a separate specialist brand where approved domain context is required.',sections:[['Intent Amplify','Buyer Intelligence + Pipeline Activation.'],['SignalAtlas','Measurement and journey intelligence within the Intent Amplify ecosystem.'],['CyberTech Intelligence','Separate specialist brand; pricing and claims remain outside the Intent Amplify commercial page unless separately approved.']],primary:['Explore SignalAtlas','/signalatlas/'],secondary:['Contact Us','/contact/']},
  '/trust/':{eyebrow:'TRUST, DATA & METHODOLOGY',h1:'TRUST IS PART OF THE GTM ARCHITECTURE.',lede:'Know what was observed, what was inferred, how identity was resolved, what is permitted for activation and what the evidence can legitimately support.',sections:[['Observed is not inferred','Keep evidence and interpretation visibly distinct.'],['Identity is not permission','Resolution does not automatically authorize activation.'],['Associated is not caused','Measurement and attribution claims require appropriate source-system evidence.']],primary:['View Data Methodology','/trust/data-methodology/'],secondary:['Contact Trust & Privacy','/contact/']},
  '/trust/data-methodology/':{eyebrow:'DATA METHODOLOGY',h1:'DEFINE → OBSERVE → RESOLVE → EXPLAIN → PRIORITIZE → ACTIVATE → PROVE.',lede:'The canonical Intent Amplify operating model separates evidence collection, identity resolution, interpretation, prioritization, activation and proof so teams can understand what each stage legitimately supports.',sections:[['Evidence classes','Observed, inferred, recommended and CRM-authoritative states remain distinct.'],['Freshness + provenance','Retain source and timing context where available.'],['Demo boundary','Illustrative SignalAtlas and account examples stay labeled DEMO/STAGING unless approved live evidence supports them.']],primary:['Explore Evidence Graph','/evidence-graph/'],secondary:['View Trust Center','/trust/']},
  '/privacy/':{eyebrow:'PRIVACY',h1:'PRIVACY CONTROLS FOR THE INTENT AMPLIFY WEBSITE.',lede:'This staging experience keeps optional analytics off until consent is granted and separates consent from identity and qualification. Final legal text, lawful bases, retention periods and subprocessors require Enterprise Governance, Evidence & Risk approval before production indexation.',sections:[['Consent','Non-essential analytics remain consent-aware in staging.'],['Data requests','Production contact and rights-handling instructions must use governance-approved legal language.']],primary:['Contact Trust & Privacy','/contact/'],secondary:['View Cookies','/cookies/']},
  '/cookies/':{eyebrow:'COOKIES',h1:'COOKIE AND ANALYTICS PREFERENCES.',lede:'The staging experience provides explicit analytics choices and does not claim a final production cookie inventory until Governance validates the deployed tag and subprocessor set.',sections:[['Essential behavior','Core site functionality should not depend on optional analytics consent.'],['Analytics choice','Optional analytics may be allowed or declined through the preference control.']],primary:['View Privacy','/privacy/'],secondary:['Contact Trust & Privacy','/contact/']},
  '/accessibility/':{eyebrow:'ACCESSIBILITY',h1:'ACCESSIBILITY IS A RELEASE REQUIREMENT.',lede:'The frontend targets accessible semantic structure, keyboard navigation, visible focus, readable contrast, reduced-motion support and clear form states. Formal compliance claims remain unverified until independent production validation.',sections:[['Keyboard + focus','Interactive controls must remain usable without a pointer.'],['Responsive readability','Mobile and desktop layouts must preserve hierarchy without horizontal overflow.']],primary:['Contact Us','/contact/'],secondary:['View Trust Center','/trust/']}
};

const nav=[['Platform','/platform/'],['Solutions','/solutions/'],['Programs','/programs/'],['Research','/research/'],['Resources','/resources/'],['SignalAtlas','/signalatlas/'],['Pricing','/pricing/'],['Company','/company/about/'],['Trust','/trust/']];
const slug=s=>s.toLowerCase().replace(/\W+/g,'_');
const go=(navigate,to,label,placement='body')=>{track('cta_click',{cta_id:slug(label),cta_text_class:label,placement,destination:to,page_type:window.location.pathname});navigate(to)};

function Header(){const n=useNavigate();return <header><a className="skip" href="#main">Skip to content</a><nav aria-label="Primary"><button className="brand" onClick={()=>n('/')}><span className="brandmark">IA</span><span>INTENT AMPLIFY</span></button><div className="navlinks">{nav.map(([x,p])=><button key={x} onClick={()=>{track('nav_click',{nav_item:x,destination:p,placement:'header'});n(p)}}>{x}</button>)}</div><button className="primary" onClick={()=>go(n,'/book-demo/','Book a Demo','header')}>Book a Demo</button></nav></header>}

function PackageCards({interactive=false}){const n=useNavigate();return <div className="grid stacks">{packages.map((s,i)=><article key={s[0]} className={i===1?'featured':''}><span className="eyebrow">0{i+1}</span><h3>{s[0]}</h3><p><strong>{s[1]}</strong></p><p>{s[2]}</p><ul>{s[3].map(x=><li key={x}>{x}</li>)}</ul>{interactive&&<button className={i===1?'primary':'textbtn'} onClick={()=>go(n,'/book-demo/',`Discuss ${s[0]}`,'pricing_card')}>Discuss {s[0]} →</button>}<small>Starting configurations in US dollars. Final scope depends on the approved commercial requirements.</small></article>)}</div>}

function Page({data}){const n=useNavigate();return <><section className="hero dark"><p className="eyebrow">{data.eyebrow}</p><h1>{data.h1}</h1><p className="lede">{data.lede}</p><div className="actions"><button className="primary" onClick={()=>go(n,data.primary[1],data.primary[0],'hero')}>{data.primary[0]}</button><button className="secondary" onClick={()=>go(n,data.secondary[1],data.secondary[0],'hero')}>{data.secondary[0]}</button></div></section><section><div className="evidenceGrid">{data.sections.map(([h,p],i)=><article key={h}><span className="eyebrow">0{i+1}</span><h2>{h}</h2><p>{p}</p></article>)}</div></section></>}

function Home(){const d=pageMap['/'];return <><Page data={d}/><section className="model"><p className="eyebrow">CANONICAL GTM MODEL</p><h2>DEFINE → OBSERVE → RESOLVE → EXPLAIN → PRIORITIZE → ACTIVATE → PROVE</h2><p>Know who is moving. Know why. Act while it matters. Every priority should be explainable.</p></section><section><p className="eyebrow">COMMERCIAL ARCHITECTURE</p><h2>Start with intelligence. Add activation when your GTM motion requires it.</h2><PackageCards interactive/></section></>}

function Pricing(){const n=useNavigate();return <><section className="hero dark"><p className="eyebrow">INTENT AMPLIFY PRICING</p><h1>START WITH INTELLIGENCE. ADD ACTIVATION WHEN YOUR GTM MOTION REQUIRES IT.</h1><p className="lede">Intent Amplify has three commercial packages. Start with buyer and account intelligence, add managed activation when your GTM motion requires it, or scope an enterprise operating model around more complex markets, programs, integrations and governance requirements. Prices shown are starting configurations in US dollars.</p><div className="actions"><button className="primary" onClick={()=>go(n,'/book-demo/','Book a Demo','pricing_hero')}>Book a Demo</button><button className="secondary" onClick={()=>go(n,'/pricing/build-your-stack/','Qualify My Package','pricing_hero')}>Qualify My Package</button></div></section><section><PackageCards interactive/><div className="summary"><h2>Commercial qualification</h2><p>Starting prices reflect baseline package configurations. Final scope and commercial terms depend on account coverage, audience size, target markets, program volume, delivery requirements, integrations, geography, research depth and governance requirements. Paid-media and third-party costs are separate unless explicitly included. Intent Amplify does not guarantee MQL, SQL, opportunity, pipeline, revenue, ROI, conversion or attribution outcomes.</p><p><strong>SignalAtlas standalone pricing remains separate. CyberTech Intelligence pricing remains separate.</strong></p></div></section></>}

const stepData=[
  ['Objective',['Improve buyer/account intelligence','Activate priority accounts','Coordinate demand + ABM','Improve sales handoff','Improve governed measurement']],
  ['Market',['Single market','Multi-market','Multi-region']],
  ['Audience',['Named-account','ICP','Buying-group context','Event-engaged','Content-engaged']],
  ['Execution',['Intelligence only','Managed activation','Multi-team enterprise motion']],
  ['Integration',['Standard website/campaign measurement','CRM linkage where approved','Advanced enterprise integration']]
];
function BuildStack(){const n=useNavigate();const[step,setStep]=useState(0);const[answers,setAnswers]=useState({});const current=stepData[step];const recommendation=useMemo(()=>{if(answers.Execution==='Multi-team enterprise motion'||answers.Integration==='Advanced enterprise integration')return'Enterprise GTM';if(answers.Execution==='Managed activation'||/Activate|Coordinate/.test(answers.Objective||''))return'Intelligence + Activation';return'Intelligence'},[answers]);return <><section className="hero dark"><p className="eyebrow">PACKAGE QUALIFICATION</p><h1>Map the GTM problem to the right commercial package.</h1><p className="lede">This staging configurator recommends one of the three approved Intent Amplify packages. It is not a binding quote, qualification decision, MQL, SQL or contractual commitment.</p></section><section className="configurator"><div className="progress" aria-label="Configurator progress">Step {Math.min(step+1,stepData.length)} of {stepData.length}</div>{step<stepData.length?<><p className="eyebrow">{current[0]}</p><h2>{current[0]}</h2><div className="choiceGrid">{current[1].map(v=><button key={v} className={answers[current[0]]===v?'choice active':'choice'} onClick={()=>{setAnswers({...answers,[current[0]]:v});track('pricing_stack_step_completed',{step_name:current[0],step_number:step+1})}}>{v}</button>)}</div><div className="actions"><button className="secondary" disabled={!step} onClick={()=>setStep(Math.max(0,step-1))}>Back</button><button className="primary" disabled={!answers[current[0]]} onClick={()=>setStep(step+1)}>Continue</button></div></>:<><p className="eyebrow">RECOMMENDATION</p><h2>{recommendation}</h2><p>Your selections indicate the {recommendation} package as the best starting point. Final commercial scope requires validation.</p><div className="summary">{Object.entries(answers).map(([k,v])=><p key={k}><strong>{k}:</strong> {v}</p>)}</div><div className="actions"><button className="primary" onClick={()=>go(n,'/book-demo/','Discuss Recommended Package','stack_result')}>Discuss Recommended Package</button><button className="secondary" onClick={()=>{setStep(0);setAnswers({})}}>Start Again</button></div></>}</section></>}

function Contact({demo=false}){const[f,setF]=useState({});const[state,setState]=useState('idle');const submit=async e=>{e.preventDefault();track('form_submit',{form_id:demo?'demo_request':'contact',form_type:demo?'demo':'contact'});setState('sending');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...f,form_id:demo?'demo_request':'contact',attribution:getAttribution(),consent:getConsent()})});const d=await r.json();if(!r.ok)throw Error(d.error);acknowledgeConversion(demo?'demo_request':'contact');track(demo?'demo_request_submitted':'contact_request_submitted',{form_id:demo?'demo_request':'contact',conversion_acknowledgement:'accepted',crm_handoff_status:d.crm_handoff_status});setState('success')}catch{track('form_validation_error',{form_id:demo?'demo_request':'contact',field_class:'form',error_class:'submission'});setState('error')}};return <section className="formpage"><p className="eyebrow">{demo?'BOOK A DEMO':'CONTACT'}</p><h1>{demo?'SEE HOW BUYER EVIDENCE BECOMES GTM ACTION.':'Tell us which GTM decision you need to improve.'}</h1><p className="lede">{demo?'Bring your ICP, target accounts or current GTM challenge. See how Intent Amplify connects buyer activity to account evidence, prioritization and the next GTM motion. A meeting request is not a qualification state.':'Tell us the declared business objective. We will acknowledge the request without labeling you MQL or SQL.'}</p><form onFocus={()=>track('form_start',{form_id:demo?'demo_request':'contact',form_type:demo?'demo':'contact'})} onSubmit={submit}>{[['first_name','First name'],['last_name','Last name'],['work_email','Work email'],['company','Company'],['role','Role / title'],['region','Country / region'],['objective','Primary objective']].map(([k,l])=><label key={k}>{l}<input required type={k==='work_email'?'email':'text'} value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<label className="consent"><input required type="checkbox"/> I agree to the applicable privacy notice for this request.</label><input className="hp" tabIndex="-1" autoComplete="off" name="website"/><button className="primary" disabled={state==='sending'}>{state==='sending'?'Submitting…':demo?'Request Your Demo':'Send Request'}</button>{state==='success'&&<p role="status">Request accepted. Staging CRM handoff is intentionally isolated.</p>}{state==='error'&&<p role="alert">We could not submit this request. Check the fields and try again.</p>}</form></section>}

function Consent(){const[c,setC]=useState(getConsent());if(c.analytics!=='unset')return null;return <aside className="cookie" aria-label="Analytics preferences"><p><strong>Analytics preferences</strong><br/>Optional analytics stay off until you allow them.</p><div><button onClick={()=>{setConsent({analytics:'denied',marketing:'denied',personalization:'denied'});setC(getConsent())}}>Decline</button><button className="primary" onClick={()=>{setConsent({analytics:'granted',marketing:'denied',personalization:'denied'});setC(getConsent())}}>Allow analytics</button></div></aside>}

function App(){const l=useLocation();const p=l.pathname==='/'?'/':`${l.pathname.replace(/\/+$/,'')}/`;useEffect(()=>{persistAttribution();track('route_view',{page_type:p,content_group:'marketing',region_variant:'global'});const title=p==='/pricing/'?'Intent Amplify Pricing':p==='/pricing/build-your-stack/'?'Package Qualification':pageMap[p]?.h1||'Evidence-led GTM';document.title=`Intent Amplify | ${title}`;window.scrollTo(0,0)},[p]);let body=p==='/'?<Home/>:p==='/pricing/'||p==='/pricing/compare/'||p==='/pricing/enterprise/'?<Pricing/>:p==='/pricing/build-your-stack/'?<BuildStack/>:p==='/contact/'?<Contact/>:p==='/book-demo/'||p==='/book-strategy-session/'?<Contact demo/>:pageMap[p]?<Page data={pageMap[p]}/>:<section className="formpage"><p className="eyebrow">404</p><h1>Page not found</h1><p>The requested route is not part of the approved staging experience.</p></section>;return <><Header/><main id="main">{body}</main><footer><strong>INTENT AMPLIFY</strong><p>Know who is moving. Understand why. Act with evidence.</p><p><a href="/platform/">Platform</a> · <a href="/programs/">Programs</a> · <a href="/research/">Research</a> · <a href="/pricing/">Pricing</a> · <a href="/resources/">Resources</a> · <a href="/trust/">Trust</a> · <a href="/privacy/">Privacy</a> · <a href="/cookies/">Cookies</a> · <a href="/accessibility/">Accessibility</a> · <a href="/contact/">Contact</a></p><p className="footerNote">Staging candidate. Illustrative account or SignalAtlas examples remain DEMO/STAGING unless backed by approved live evidence. Website activity does not automatically create MQL, SQL, opportunity, pipeline or revenue states.</p></footer><Consent/></>}
export default App;