import React,{useMemo,useState}from'react';
import{createPortal}from'react-dom';
import{useLocation,useNavigate}from'react-router-dom';
import{track}from'./analytics';

const RESOURCE_TYPES=[
  {label:'Blogs',path:'https://intentamplify.com/blog/',description:'Practical GTM, buyer, demand and revenue-team guidance.',cta:'Browse Blogs'},
  {label:'Corporate Presentation 2026',path:'https://intentamplify.com/mediakit/',description:'Intent Amplify corporate and commercial overview.',cta:'View Corporate Presentation'},
  {label:'Ebooks',path:'https://intentamplify.com/ebooks/',description:'Long-form guides for GTM education and decision support.',cta:'Browse Ebooks'},
  {label:'Case Studies',path:'https://intentamplify.com/case-study/',description:'Case-study destination. Customer outcomes remain unpublished unless approved.',cta:'Browse Case Studies'},
  {label:'Newsletters',path:'https://intentamplify.com/newsletters/',description:'Recurring editorial intelligence for GTM teams.',cta:'Browse Newsletters'},
  {label:'Whitepapers',path:'https://intentamplify.com/whitepapers/',description:'Decision frameworks for enterprise GTM questions.',cta:'Browse Whitepapers'},
  {label:'Expert Insights',path:'https://intentamplify.com/expert-insights/',description:'Focused practitioner perspectives on market and GTM change.',cta:'Browse Expert Insights'},
  {label:'Expert Analysis',path:'https://intentamplify.com/expert-analysises/',description:'Deeper analytical perspectives for executive and functional buyers.',cta:'Browse Expert Analysis'},
  {label:'Research Reports',path:'https://intentamplify.com/reports/',description:'Research-led reports for market understanding and decision support.',cta:'Browse Research Reports'}
];

const RESOURCES=[
{id:'ebook-hub',status:'VERIFIED EXISTING',type:'Ebook Library',title:'B2B Lead Generation eBooks',description:'Intent Amplify’s established ebook library for long-form GTM and buyer education.',topic:'GTM Education',industry:'B2B Technology',persona:'Marketing & Revenue',source:'Intent Amplify',url:'https://intentamplify.com/ebooks/',cta:'Browse Ebooks',objective:'Learn'},
{id:'report-hub',status:'VERIFIED EXISTING',type:'Research Library',title:'B2B Demand Intelligence Reports',description:'Intent Amplify’s report library for research-led demand, market and operating insights.',topic:'Demand Intelligence',industry:'B2B Technology',persona:'CMO & GTM Leadership',source:'Intent Amplify',url:'https://intentamplify.com/reports/',cta:'Browse Reports',objective:'Understand'},
{id:'whitepaper-hub',status:'VERIFIED EXISTING',type:'Whitepaper Library',title:'Demand Intelligence Whitepapers',description:'Whitepapers for teams examining market, buyer and operating questions in greater depth.',topic:'Buyer Intelligence',industry:'B2B Technology',persona:'Marketing & Strategy',source:'Intent Amplify',url:'https://intentamplify.com/whitepapers/',cta:'Browse Whitepapers',objective:'Understand'},
{id:'sap-webinar',status:'VERIFIED EXISTING',type:'Webinar',title:'SAP AI Inside the Supply Chain: From Silo to Orchestration',description:'Existing Intent Amplify webinar destination focused on AI and supply-chain orchestration. Current live/on-demand status is not asserted.',topic:'AI & Operations',industry:'Supply Chain',persona:'Operations & Technology',source:'Intent Amplify',url:'https://intentamplify.com/landing-page/webinar/sap-ai-inside-the-supply-chain-from-silo-to-orchestration/',cta:'View Webinar',objective:'Understand'},
{id:'dmu',status:'VERIFIED EXISTING',type:'Blog',title:'Decision Making Unit (DMU) in B2B: Roles, Strategy & Examples',description:'Existing Intent Amplify guide to B2B decision-making units and the roles shaping complex purchases.',topic:'Buying Groups',industry:'B2B Technology',persona:'ABM & Sales',source:'Intent Amplify',url:'https://intentamplify.com/blog/b2b-decision-making-unit-dmu/',cta:'Read Guide',objective:'Understand'},
{id:'buyer-process',status:'VERIFIED EXISTING',type:'Blog',title:'B2B Buying Process: 6 Stages, Key Stakeholders & Strategies for 2026',description:'Existing guide to buying-stage progression and stakeholder context.',topic:'Buyer Journey',industry:'B2B Technology',persona:'Marketing & Sales',source:'Intent Amplify',url:'https://intentamplify.com/blog/b2b-buying-decision-process/',cta:'Read Guide',objective:'Understand'},
{id:'tam-tal',status:'VERIFIED EXISTING',type:'Blog',title:'TAM vs TAL in B2B: Definitions, Formulas & How to Build a TAL',description:'Existing guide to total addressable market versus target-account-list design.',topic:'ABM',industry:'B2B Technology',persona:'ABM & Strategy',source:'Intent Amplify',url:'https://intentamplify.com/blog/tam-vs-tal-in-b2b-whats-the-difference/',cta:'Read Guide',objective:'Define'},
{id:'logistics',status:'VERIFIED EXISTING',type:'Research Report',title:'Logistics Resilience 2026: Visibility and Risk Management',description:'Existing research destination focused on logistics resilience, visibility and risk-management priorities.',topic:'Market Intelligence',industry:'Supply Chain',persona:'Operations Leadership',source:'Intent Amplify',url:'https://intentamplify.com/report/logistics-resilience-2026-visibility-risk-management/',cta:'Read Report',objective:'Understand'},
{id:'physical-security',status:'VERIFIED EXISTING',type:'Research Report',title:'Cloud, AI Video, and Access Governance Trends in Enterprise Physical Security',description:'Existing research destination examining cloud, AI video and governance themes in enterprise physical security.',topic:'Security & Governance',industry:'Cybersecurity',persona:'Security Leadership',source:'Intent Amplify',url:'https://intentamplify.com/report/enterprise-physical-security-trends/',cta:'Read Report',objective:'Understand'},
{id:'playbook',status:'NEW ORIGINAL CONTENT',type:'GTM Playbook',title:'The Explainable Account Priority Playbook',description:'A new Intent Amplify editorial concept: define the target market, observe account evidence, separate direct observations from interpretation, explain why an account deserves attention and choose the permitted next motion.',topic:'Buyer Intelligence',industry:'B2B Technology',persona:'Demand, ABM & RevOps',source:'Intent Amplify Editorial',url:'/platform/',cta:'Explore the Operating Model',objective:'Inspect Evidence'},
{id:'handoff-guide',status:'NEW ORIGINAL CONTENT',type:'GTM Guide',title:'From Content Engagement to Sales Handoff—Without Inventing an SQL',description:'A practical guide concept for preserving source, recency, consent and account context as engagement moves toward sales review while keeping qualification authoritative.',topic:'Sales Handoff',industry:'B2B Technology',persona:'Marketing, SDR & RevOps',source:'Intent Amplify Editorial',url:'/trust/data-methodology/',cta:'View the Methodology',objective:'Inspect Evidence'}
];
const PLANNED_EVENTS=[
{id:'planned-buyer-evidence',status:'PLANNED',type:'Webinar Concept',title:'From Buyer Signals to Explainable Account Priority',description:'Editorial webinar concept on combining fit, engagement and intent evidence without turning activity into automatic qualification.',topic:'Buyer Intelligence',industry:'B2B Technology',persona:'Demand, ABM & RevOps',source:'Intent Amplify Editorial',url:'/book-demo/',cta:'Discuss This GTM Motion',objective:'Understand'},
{id:'planned-abm',status:'PLANNED',type:'Executive Session Concept',title:'ABM After the Score: Building the Why-Now Account Brief',description:'Planned session concept showing how account evidence can become a useful GTM and SDR context brief. No speaker, date or registration claim is made.',topic:'ABM',industry:'B2B Technology',persona:'ABM & Sales',source:'Intent Amplify Editorial',url:'/book-demo/',cta:'Discuss an ABM Motion',objective:'Explore Capability'},
{id:'planned-measurement',status:'PLANNED',type:'Webinar Concept',title:'Observed, Inferred, Qualified: A Practical GTM Measurement Model',description:'Planned session concept on evidence classes, consent, identity boundaries and CRM-authoritative lifecycle states.',topic:'Measurement',industry:'B2B Technology',persona:'RevOps & GTM Leadership',source:'Intent Amplify Editorial',url:'/trust/data-methodology/',cta:'Explore Data Methodology',objective:'Inspect Evidence'}
];
const TOPICS=['Buying Groups','Buyer Intelligence','ABM','Demand Intelligence','Buyer Journey','Market Intelligence','Security & Governance','AI & Operations','Sales Handoff','Measurement'];
const uniq=(items,key)=>[...new Set(items.map(x=>x[key]).filter(Boolean))];
const openTrack=item=>track('resource_open',{resource_id:item.id,resource_type:item.type,resource_topic:item.topic,resource_source:item.source,resource_objective:item.objective,resource_status:item.status,placement:'resources'});

function ResourceCard({item,featured=false}){const internal=item.url.startsWith('/');return <article className={featured?'resourceCard resourceFeaturedCard':'resourceCard'}><div className="resourceCardTop"><span className="resourceBadge">{item.status}</span><span className="resourceUnverified">{item.type}</span></div><h3>{item.title}</h3><p>{item.description}</p><dl className="resourceMeta"><div><dt>Topic</dt><dd>{item.topic}</dd></div><div><dt>Industry</dt><dd>{item.industry}</dd></div><div><dt>Role / Team</dt><dd>{item.persona}</dd></div><div><dt>GTM objective</dt><dd>{item.objective}</dd></div><div><dt>Source</dt><dd>{item.source}</dd></div></dl><a className="resourceLink" href={item.url} target={internal?undefined:'_blank'} rel={internal?undefined:'noreferrer'} onClick={()=>openTrack(item)}>{item.cta} →</a></article>}
function FilterChips({label,values,active,onChange}){return <div className="resourceFilterGroup"><span>{label}</span><div className="resourceChips"><button className={active==='All'?'active':''} onClick={()=>onChange('All')}>All</button>{values.map(v=><button key={v} className={active===v?'active':''} onClick={()=>onChange(v)}>{v}</button>)}</div></div>}

function ResourceExperience(){const loc=useLocation();const navigate=useNavigate();const[topic,setTopic]=useState('All');const[industry,setIndustry]=useState('All');const[persona,setPersona]=useState('All');const[objective,setObjective]=useState('All');const filtered=useMemo(()=>RESOURCES.filter(x=>(topic==='All'||x.topic===topic)&&(industry==='All'||x.industry===industry)&&(persona==='All'||x.persona===persona)&&(objective==='All'||x.objective===objective)),[topic,industry,persona,objective]);if(loc.pathname.replace(/\/+$/,'')!=='/resources')return null;const target=typeof document!=='undefined'?document.querySelector('main'):null;if(!target)return null;const research=RESOURCES.filter(x=>/Research|Whitepaper/.test(x.type));const reset=()=>{setTopic('All');setIndustry('All');setPersona('All');setObjective('All')};return createPortal(<div className="resourceExperience" aria-label="Intent Amplify resource discovery">
<section className="resourceSection resourceIntro"><p className="eyebrow">RESEARCH / RESOURCES / EVENTS</p><div className="resourceFeature"><div><h2>Intelligence for the GTM decision in front of you.</h2><p>Learn the market. Understand the buying context. Inspect the evidence and methodology. Explore the relevant Intent Amplify capability. Start a GTM conversation when the problem is defined.</p><div className="resourceJourney"><span>Learn</span><b>→</b><span>Understand</span><b>→</b><span>Inspect Evidence</span><b>→</b><span>Explore Capability</span><b>→</b><span>Book a Demo</span></div></div><ResourceCard item={RESOURCES.find(x=>x.id==='dmu')} featured/></div></section>
<section className="resourceSection resourceAlt"><div className="resourceSectionHead"><div><p className="eyebrow">BROWSE BY TYPE</p><h2>One editorial front door. Clear paths into the existing content estate.</h2></div><p>Existing destinations remain intact. Missing customer outcomes, dates, speakers or author metadata are not fabricated.</p></div><div className="resourceTypeGrid">{RESOURCE_TYPES.map(x=><a key={x.label} className="resourceTypeCard" href={x.path} target="_blank" rel="noreferrer"><span>VERIFIED EXISTING · {x.label}</span><p>{x.description}</p><strong>{x.cta} →</strong></a>)}</div></section>
<section className="resourceSection"><div className="resourceSectionHead"><div><p className="eyebrow">RESEARCH EXPERIENCE</p><h2>Move from market context to the evidence behind the GTM decision.</h2></div><p>Verified existing research is separated from new Intent Amplify editorial concepts.</p></div><div className="resourceGrid">{research.map(x=><ResourceCard key={x.id} item={x}/>)}</div></section>
<section className="resourceSection resourceAlt"><div className="resourceSectionHead"><div><p className="eyebrow">EVENTS / WEBINARS</p><h2>Existing webinar content plus clearly labeled planned editorial concepts.</h2></div><p>PLANNED concepts have no invented date, speaker, registration status or external fact.</p></div><div className="resourceEventGrid"><ResourceCard item={RESOURCES.find(x=>x.id==='sap-webinar')} featured/><div className="resourceGrid">{PLANNED_EVENTS.map(x=><ResourceCard key={x.id} item={x}/>)}</div></div></section>
<section className="resourceSection"><div className="resourceSectionHead"><div><p className="eyebrow">NEW ORIGINAL CONTENT</p><h2>Fill the ABM journey with original, evidence-safe Intent Amplify editorial concepts.</h2></div><p>These concepts are staging editorial content, not historical claims.</p></div><div className="resourceGrid">{RESOURCES.filter(x=>x.status==='NEW ORIGINAL CONTENT').map(x=><ResourceCard key={x.id} item={x}/>)}</div></section>
<section className="resourceSection resourceAlt"><div className="resourceSectionHead"><div><p className="eyebrow">TRENDING GTM TOPICS</p><h2>Choose the account question you need to answer.</h2></div><p>Topic navigation is editorial; it is not a market-ranking claim.</p></div><div className="topicCloud">{TOPICS.map(v=><button key={v} onClick={()=>setTopic(v)}>{v}</button>)}</div></section>
<section className="resourceSection"><div className="resourceSectionHead"><div><p className="eyebrow">ABM CONTENT STACK</p><h2>Move the account forward without pretending engagement is qualification.</h2></div><p>Resource behaviour is evidence for prioritization. It is not, by itself, MQL, SQL, opportunity, pipeline or revenue proof.</p></div><div className="resourceABMStack"><article><span>DEFINE</span><h3>Market + TAL</h3><p>Use market, ICP and TAM/TAL content to sharpen the account universe.</p><button className="textbtn" onClick={()=>setObjective('Define')}>View Define content →</button></article><article><span>OBSERVE</span><h3>Engagement</h3><p>Use content consumption as one observed signal, preserving source and context.</p><button className="textbtn" onClick={()=>setObjective('Learn')}>View Learn content →</button></article><article><span>EXPLAIN</span><h3>Buying context</h3><p>Connect topic interest with account and buying-context evidence before prioritization.</p><button className="textbtn" onClick={()=>setObjective('Understand')}>View Understand content →</button></article><article><span>ACTIVATE</span><h3>Capability path</h3><p>Route relevant interest toward the appropriate platform, program or GTM conversation.</p><button className="textbtn" onClick={()=>setObjective('Explore Capability')}>View Capability content →</button></article><article><span>PROVE</span><h3>Sales acceptance</h3><p>Demo requests can create a handoff candidate. SQL requires approved CRM criteria and sales validation.</p><button className="textbtn" onClick={()=>navigate('/book-demo/')}>Book a Demo →</button></article></div></section>
<section className="resourceSection resourceAlt"><div className="resourceSectionHead"><div><p className="eyebrow">CONTENT DISCOVERY</p><h2>Filter verified and original content by topic, industry, role or GTM objective.</h2></div><button className="textbtn" onClick={reset}>Reset filters</button></div><div className="resourceFilterPanel"><FilterChips label="Topic" values={uniq(RESOURCES,'topic')} active={topic} onChange={setTopic}/><FilterChips label="Industry" values={uniq(RESOURCES,'industry')} active={industry} onChange={setIndustry}/><FilterChips label="Role / Team" values={uniq(RESOURCES,'persona')} active={persona} onChange={setPersona}/><FilterChips label="GTM Objective" values={uniq(RESOURCES,'objective')} active={objective} onChange={setObjective}/></div>{filtered.length?<div className="resourceGrid resourceGridThree">{filtered.map(x=><ResourceCard key={x.id} item={x}/>)}</div>:<div className="resourceEmpty"><strong>No resource matches this combination.</strong><p>Reset the filters or choose a broader discovery path. No placeholder asset is invented.</p></div>}</section>
<section className="resourceSection"><div className="resourceConversion"><div><span className="eyebrow">BUYER INTELLIGENCE + PIPELINE ACTIVATION</span><h2>Connect what the account is learning to what GTM should inspect next.</h2><p>Intent Amplify connects account, buying-group, intent and engagement signals into traceable buyer evidence, then helps teams coordinate the next GTM action. Resource engagement remains an observed signal—not automatic qualification.</p></div><div className="actions"><button className="secondary" onClick={()=>navigate('/platform/')}>Explore the Platform</button><button className="primary" onClick={()=>navigate('/book-demo/')}>Book a Demo</button></div></div></section>
</div>,target)}
export default ResourceExperience;